name: windows cmake msvc

on:
  [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_DEBUG_BIN_PATH: ${{ github.workspace }}/builds/ninja-multi-vcpkg/vcpkg_installed/x64-windows/debug/bin
      VCPKG_BIN_PATH: ${{ github.workspace }}/builds/ninja-multi-vcpkg/vcpkg_installed/x64-windows/bin

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@v3.27.6

    - name: Download xvid
      id: download_xvid
      shell: bash
      run: |
        mkdir ../xvid
        cd ../xvid
        curl -LO "https://github.com/ShiftMediaProject/xvid/releases/download/release-1_3_7/libxvidcore_release-1_3_7_msvc16.zip"
        unzip libxvidcore_release-1_3_7_msvc16.zip
        mkdir "C:/Program Files/XviD"
        mkdir "C:/Program Files/XviD/include"
        mkdir "C:/Program Files/XviD/lib"
        mkdir "C:/Program Files/XviD/bin"
        mv include/xvid.h "C:/Program Files/XviD/include/"
        mv lib/x64/xvidcore.lib "C:/Program Files/XviD/lib/"
        mv lib/x64/libxvidcore.lib "C:/Program Files/XviD/lib/"
        mv bin/x64/xvidcore.dll "C:/Program Files/XviD/bin/"
        cd -
        rm -rf ../xvid

    - name: Prepare vcpkg
      id: prepare_vcpkg
      shell: bash
      run: |
        mkdir -vp "${VCPKG_DEFAULT_BINARY_CACHE}"
        cp -v "${GITHUB_WORKSPACE}"/.github/workflows/vcpkg.json "${GITHUB_WORKSPACE}"/
        cp -v "${GITHUB_WORKSPACE}"/.github/workflows/CMakePresets.json "${GITHUB_WORKSPACE}"/

    - name: Restore artifacts and set up vcpkg
      uses: lukka/run-vcpkg@v11
      id: run_vcpkg
      with:
        vcpkgGitCommitId: accd79817981f1ce00c6a4164aecf2b2ac699823
        vcpkgJsonGlob: vcpkg.json

    - name: Add dll paths to PATH
      id: add_dll_path
      run: |
        echo $env:VCPKG_BIN_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo $env:VCPKG_DEBUG_BIN_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:/Program Files/XviD/bin"  | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Run CMake, with vcpkg stage, generate, build and test
      uses: lukka/run-cmake@v10
      id: run_cmake
      with:
        configurePreset: ninja-multi-vcpkg
        buildPreset: ninja-multi-vcpkg-debug
        testPreset: ninja-multi-vcpkg-debug
